"""
neuroforge/mlops/model_card.py
================================
Automated FDA/EMA SaMD Model Card generator.

Produces a structured model card JSON + Markdown following:
  - FDA Software as a Medical Device (SaMD) Pre-Spec framework
  - EU AI Act Annex IV High-Risk AI documentation requirements
  - Model Cards for Model Reporting (Mitchell et al., 2019)
"""
from __future__ import annotations
import json
import platform
import sys
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from neuroforge.core.config import (
    FHIR_DEVICE_ID, SEED, N_ECOG_CHANNELS,
    D_MODEL, N_HEADS, N_TRANSFORMER_LAYERS,
    IZH_A, IZH_B, IZH_C, IZH_D,
)
from neuroforge.core.logger import get_logger

log = get_logger(__name__)

CARD_OUTPUT_DIR = Path(__file__).parents[2] / "model_cards"
CARD_OUTPUT_DIR.mkdir(exist_ok=True)


def generate_model_card(
    architecture_version: str = "3.0.0",
    training_steps: int = 0,
    mae_loss: float = float("nan"),
    contrastive_loss: float = float("nan"),
    mean_sqi: float = float("nan"),
    decoder_latency_ms: float = float("nan"),
    ablation_results: dict[str, float] | None = None,
    intended_population: str = (
        "Adults (18+) with complete SCI (AIS-A), Brainstem Stroke, or ALS. "
        "Contraindicated for pediatric use or active cardiac implants."
    ),
    out_of_scope: str = (
        "Emotion decoding, speech-BCI, diagnostic imaging analysis. "
        "Not validated for incomplete SCI (AIS-B/C/D)."
    ),
) -> Path:
    """
    Generate a structured model card for regulatory audit.

    Returns:
        Path to saved JSON model card.
    """
    card: dict[str, Any] = {
        "model_card_version": "1.0",
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "device_id": FHIR_DEVICE_ID,
        "regulatory_framework": {
            "FDA": "SaMD Pre-Specification (PreS) — Predetermined Change Control Plan",
            "EU_AI_Act": "Annex IV High-Risk AI System — Article 13 Transparency",
            "ISO": ["ISO 14708-1 (Implantable)", "ISO 10993 (Biocompatibility)"],
        },
        "model_details": {
            "architecture": "NeuroForge CANRP-X v3.0 — Ensemble Neuro-AI Decoder",
            "version": architecture_version,
            "components": [
                "Masked Neural Autoencoder (MNA) — Transformer Encoder",
                "SimCLR Contrastive Self-Supervised Pretraining",
                "Temporal Patch-Transformer Decoder",
                "Bi-directional Mamba-inspired SSM Decoder",
                "Dynamic Bayesian Model Averaging",
                "Izhikevich Spiking CPG (N_flexor=20, N_extensor=20)",
                "Triplet STDP Synaptic Plasticity Engine",
                "Non-linear Model Predictive Control (SLSQP, T=10)",
                "Riemannian Procrustes Domain Alignment",
            ],
            "hyperparameters": {
                "n_ecog_channels": N_ECOG_CHANNELS,
                "d_model": D_MODEL,
                "n_attention_heads": N_HEADS,
                "transformer_layers": N_TRANSFORMER_LAYERS,
                "random_seed": SEED,
                "izhikevich_params": {"a": IZH_A, "b": IZH_B, "c": IZH_C, "d": IZH_D},
            },
        },
        "intended_use": {
            "primary_purpose": (
                "Decode cortical motor intent from μECoG signals and deliver "
                "phase-locked epidural spinal cord stimulation for motor restoration "
                "in patients with complete paralysis."
            ),
            "intended_users": "Implanting neurosurgeons, rehabilitation engineers, clinical operators.",
            "intended_population": intended_population,
            "out_of_scope_uses": out_of_scope,
        },
        "training_data": {
            "description": (
                "Synthetic multimodal data generated by coupled Jansen-Rit neural mass "
                "models, Izhikevich CPG simulation, and MuJoCo 14-DoF biomechanical model."
            ),
            "real_world_data": "Not yet included (TRL 1–3 software-only stage).",
            "bias_notes": (
                "Synthetic data may not fully capture inter-subject electrode drift, "
                "pathological epileptiform activity, or chronic impedance degradation."
            ),
        },
        "performance_metrics": {
            "training_steps": training_steps,
            "mae_reconstruction_loss": round(mae_loss, 6) if mae_loss == mae_loss else "not_evaluated",
            "simclr_contrastive_loss": round(contrastive_loss, 6) if contrastive_loss == contrastive_loss else "not_evaluated",
            "mean_signal_quality_index": round(mean_sqi, 4) if mean_sqi == mean_sqi else "not_evaluated",
            "closed_loop_latency_ms": round(decoder_latency_ms, 2) if decoder_latency_ms == decoder_latency_ms else "not_evaluated",
            "latency_target_ms": 15.0,
            "latency_compliant": decoder_latency_ms < 15.0 if decoder_latency_ms == decoder_latency_ms else "unknown",
        },
        "ablation_study": ablation_results or {},
        "safety_mechanisms": [
            "Shannon charge-density k-limit (≤1.75) enforced per stimulation pulse.",
            "Fall-reflex IMU interlock (>300°/s → 85Nm bracing, <250μs).",
            "Cole-Cole α<0.70 biofouling alert with auto voltage scaling.",
            "XAI artifact-dominance alert (low-freq > high-gamma attribution).",
            "Thermal throttling at ΔT > 0.8°C (ISO 14708-1).",
            "Hardware fallback interlock: <250μs limp-stance trip.",
        ],
        "explainability": {
            "method": "Path Integrated Gradients + Frequency-Band Decomposition",
            "real_time": True,
            "regulatory_relevance": (
                "Verifies that beta desynchronization and high-gamma activity "
                "drive stimulation decisions, not motion artifacts or line noise."
            ),
        },
        "compute_envelope": {
            "platform": platform.system(),
            "python": sys.version,
            "cpu_optimized": True,
            "gpu_required": False,
            "embedded_target": "22nm FD-SOI RISC-V dual-core SoC (<11.4 mW)",
        },
        "reproducibility": {
            "random_seed": SEED,
            "environment_lockfile": "requirements.txt + conda-lock.yml",
            "deterministic": True,
        },
        "audit_trail": {
            "generated_timestamp": datetime.now(timezone.utc).isoformat(),
            "card_hash": None,   # filled below after serialisation
        },
    }

    # Compute self-referencing hash
    card_str = json.dumps(card, sort_keys=True)
    import hashlib
    card["audit_trail"]["card_hash"] = hashlib.sha256(card_str.encode()).hexdigest()

    # Save JSON
    ts = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    json_path = CARD_OUTPUT_DIR / f"model_card_{ts}.json"
    json_path.write_text(json.dumps(card, indent=2), encoding="utf-8")

    # Save Markdown version
    md_path = CARD_OUTPUT_DIR / f"model_card_{ts}.md"
    md = _card_to_markdown(card)
    md_path.write_text(md, encoding="utf-8")

    log.info("Model card generated → %s", json_path)
    return json_path


def _card_to_markdown(card: dict[str, Any]) -> str:
    """Convert model card dict to readable Markdown."""
    lines = [
        "# NeuroForge CANRP-X Model Card",
        f"**Generated:** {card['generated_at']}  ",
        f"**Device ID:** {card['device_id']}",
        "",
        "## Regulatory Frameworks",
    ]
    for k, v in card["regulatory_framework"].items():
        lines.append(f"- **{k}**: {v}")

    lines += ["", "## Model Architecture"]
    for comp in card["model_details"]["components"]:
        lines.append(f"- {comp}")

    lines += ["", "## Intended Use"]
    lines.append(card["intended_use"]["primary_purpose"])
    lines.append(f"\n**Intended population:** {card['intended_use']['intended_population']}")
    lines.append(f"\n**Out of scope:** {card['intended_use']['out_of_scope_uses']}")

    lines += ["", "## Performance Metrics"]
    for k, v in card["performance_metrics"].items():
        lines.append(f"- **{k}**: {v}")

    lines += ["", "## Safety Mechanisms"]
    for s in card["safety_mechanisms"]:
        lines.append(f"- {s}")

    lines += ["", "## Explainability"]
    lines.append(f"- **Method:** {card['explainability']['method']}")
    lines.append(f"- **Real-time:** {card['explainability']['real_time']}")

    lines += [
        "", "## Reproducibility",
        f"- **Seed:** {card['reproducibility']['random_seed']}",
        f"- **Deterministic:** {card['reproducibility']['deterministic']}",
        f"- **Lockfile:** {card['reproducibility']['environment_lockfile']}",
        "", f"*Audit hash: `{card['audit_trail']['card_hash']}`*",
    ]
    return "\n".join(lines)
